project:
  type: book

book:
  reader-mode: true
  page-footer:
    center: "Andrew J. Thurston © 2025"
  license: "Andrew J. Thurston © 2025"
  title: "Organizational Data Visualization"
  subtitle: "orgdataviz.com"
  cover-image: /images/bull.jpg
  author: "AJ Thurston"
  date: "12/29/2024"
  chapters:
    - index.qmd
    - intro/index.qmd
    - text: "Time"
      href: time/index.qmd
    - text: "Categories"
      href: categories/index.qmd
    - text: "Relationships: Descriptive"
      href: describingrelationships/index.qmd
    - text: "Relationships: Explanatory"
      href: explainingrelationships/index.qmd
    - text: "Space"
      href: space/index.qmd
    - text: "Interactive"
      href: interactive/index.qmd
    - text: "Context"
      href: context/index.qmd
    - resources/index.qmd
    - references/index.qmd
  sidebar:
    pinned: true
    search: true
    title: "ODV"
    
  repo-url: https://github.com/AJThurston/orgdataviz  
  search: 
    location: sidebar
    type: textbox
#  downloads: [pdf, epub]

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly 
    toc: true
    toc-expand: 3
  #pdf:
    #documentclass: scrreprt

editor: source

