project:
  type: book

book:
  reader-mode: true
  page-footer:
    center: "Andrew J. Thurston © 2025"
  license: "Andrew J. Thurston © 2025"
  title: "Organizational Data Visualization"
  subtitle: "orgdataviz.com"
  cover-image: /images/bull.jpg
  author: "AJ Thurston"
  date: "12/29/2024"
  chapters:
    - index.qmd
    - intro/index.qmd
    - time/index.qmd
    - categories/index.qmd
    - reldescrib/index.qmd
    - relexplain/index.qmd
    - space/index.qmd
    - interact/index.qmd
    - context/index.qmd
    - resources/index.qmd
    - references/index.qmd
  sidebar:
    pinned: true
    search: true
    title: "ODV"
    
  repo-url: https://github.com/AJThurston/orgdataviz  
  search: 
    location: sidebar
    type: textbox
#  downloads: [pdf, epub]

# bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly 
  #pdf:
    #documentclass: scrreprt

editor: visual

