project:
  type: book

book:
  reader-mode: false
  page-footer:
    center: "Andrew J. Thurston © 2025"
  license: "Andrew J. Thurston © 2025"
  title: "Organizational Data Visualization"
  subtitle: "Communicating clearly, concisely, and convincingly"
  description: "orgdataviz.com"
  output-file: "orgdataviz"
#  cover-image: /images/cover.png
  sharing: [twitter, linkedin]
  author: "AJ Thurston"
  date: "01/01/2025"
  chapters:
    - index.qmd
    - intro/index.qmd
    - text: "Time"
      href: time/index.qmd
    - text: "Categories"
      href: categories/index.qmd
    - text: "Relationships: Descriptive"
      href: describingrelationships/index.qmd
    - text: "Relationships: Explanatory"
      href: explainingrelationships/index.qmd
    - text: "Space"
      href: space/index.qmd
    - text: "Interactive"
      href: interactive/index.qmd
    - text: "Context"
      href: context/index.qmd
    - resources/index.qmd
    - references/index.qmd
  sidebar:
    pinned: true
    search: true
    title: "ODV"
    
  repo-url: https://github.com/AJThurston/orgdataviz  
  search: 
    location: sidebar
    type: textbox
  downloads: pdf

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly 
    toc: true
    toc-expand: 3
  pdf:
    cover-image: /images/cover.png
    documentclass: scrbook

editor: source

